# Generated by Django 3.1.1 on 2020-09-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matmateuser',
            options={'verbose_name': '매트메이트 사용자', 'verbose_name_plural': '매트메이트 사용자'},
        ),
        migrations.AddField(
            model_name='matmateuser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matmateuser',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
